"""empty message

Revision ID: 0862e5b47932
Revises: 40c60080982f
Create Date: 2022-12-27 21:07:04.880307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0862e5b47932'
down_revision = '40c60080982f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depature_tbl')
    op.add_column('bus_tbl', sa.Column('bus_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bus_tbl', 'bus_capacity')
    op.create_table('depature_tbl',
    sa.Column('dep_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seats_available', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booked_seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dep_id', name='depature_tbl_pkey')
    )
    # ### end Alembic commands ###
