"""empty message

Revision ID: 09e38f5d97e1
Revises: 6c0afdedf779
Create Date: 2022-12-31 18:38:56.053950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e38f5d97e1'
down_revision = '6c0afdedf779'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
