"""empty message

Revision ID: 40c60080982f
Revises: 7722411dd7ff
Create Date: 2022-12-26 18:17:35.349107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c60080982f'
down_revision = '7722411dd7ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depature_tbl',
    sa.Column('dep_id', sa.Integer(), nullable=False),
    sa.Column('seats_available', sa.Integer(), nullable=False),
    sa.Column('booked_seats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('dep_id')
    )
    op.create_table('users_tbl',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_passenger', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('is_driver', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('travel_route_tbl',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('leaving_from', sa.String(), nullable=False),
    sa.Column('going_to', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_tbl.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('bus_tbl',
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('bus_name', sa.String(), nullable=False),
    sa.Column('no_of_seats', sa.Integer(), nullable=False),
    sa.Column('seat_arrangement', sa.String(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['travel_route_tbl.route_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_tbl.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bus_id')
    )
    op.create_table('book_ticket_tbl',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('leaving_from', sa.String(), nullable=False),
    sa.Column('going_to', sa.String(), nullable=False),
    sa.Column('travel_status', sa.String(), server_default='upcoming', nullable=False),
    sa.Column('travel_type', sa.String(), server_default='oneway', nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('seat_no', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['bus_tbl.bus_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users_tbl.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_ticket_tbl')
    op.drop_table('bus_tbl')
    op.drop_table('travel_route_tbl')
    op.drop_table('users_tbl')
    op.drop_table('depature_tbl')
    # ### end Alembic commands ###
