"""empty message

Revision ID: 4a08a2884310
Revises: f979fc8be187
Create Date: 2022-12-30 18:55:27.662021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a08a2884310'
down_revision = 'f979fc8be187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_tbl',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['bus_tbl.bus_id'], ),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('bus_id')
    )
    op.add_column('users_tbl', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users_tbl', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users_tbl', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('users_tbl', 'is_driver')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tbl', sa.Column('is_driver', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users_tbl', 'phone_number')
    op.drop_column('users_tbl', 'last_name')
    op.drop_column('users_tbl', 'first_name')
    op.drop_table('driver_tbl')
    # ### end Alembic commands ###
