"""empty message

Revision ID: 5bbfec2fff9d
Revises: 0862e5b47932
Create Date: 2022-12-27 21:21:47.732723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbfec2fff9d'
down_revision = '0862e5b47932'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bus_tbl', 'bus_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bus_tbl', 'bus_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
