"""empty message

Revision ID: 5f014024c4a5
Revises: 6e7f01a93dc0
Create Date: 2023-01-01 15:54:09.066523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f014024c4a5'
down_revision = '6e7f01a93dc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
