"""empty message

Revision ID: 685497c22089
Revises: f777582fdee5
Create Date: 2022-12-29 00:02:32.304378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685497c22089'
down_revision = 'f777582fdee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments_tbl', ['ticket_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments_tbl', type_='unique')
    # ### end Alembic commands ###
