"""empty message

Revision ID: 6c0afdedf779
Revises: 4a08a2884310
Create Date: 2022-12-30 19:53:05.265527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0afdedf779'
down_revision = '4a08a2884310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookedseats_tbl',
    sa.Column('seats_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('booked_seats', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus_tbl.bus_id'], ),
    sa.PrimaryKeyConstraint('seats_id'),
    sa.UniqueConstraint('bus_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookedseats_tbl')
    # ### end Alembic commands ###
