"""empty message

Revision ID: 6e7f01a93dc0
Revises: 02ee53d341f6
Create Date: 2023-01-01 15:24:29.648379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7f01a93dc0'
down_revision = '02ee53d341f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
