"""routes in depature 

Revision ID: 826dc2589d0a
Revises: f8ce0141c696
Create Date: 2023-01-14 18:30:16.556070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826dc2589d0a'
down_revision = 'f8ce0141c696'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depature_tbl', sa.Column('route_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'depature_tbl', 'travel_route_tbl', ['route_id'], ['route_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'depature_tbl', type_='foreignkey')
    op.drop_column('depature_tbl', 'route_id')
    # ### end Alembic commands ###
