"""empty message

Revision ID: 97bd84899af2
Revises: ef1ffe7b6319
Create Date: 2022-12-29 01:53:36.361301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bd84899af2'
down_revision = 'ef1ffe7b6319'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tbl', sa.Column('f_name', sa.String(), nullable=True))
    op.add_column('users_tbl', sa.Column('l_name', sa.String(), nullable=True))
    op.add_column('users_tbl', sa.Column('phone_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_tbl', 'phone_number')
    op.drop_column('users_tbl', 'l_name')
    op.drop_column('users_tbl', 'f_name')
    # ### end Alembic commands ###
