"""empty message

Revision ID: f777582fdee5
Revises: 89f891f4ed7e
Create Date: 2022-12-28 22:48:57.390484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f777582fdee5'
down_revision = '89f891f4ed7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_ticket_tbl', sa.Column('travel_date', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_ticket_tbl', 'travel_date')
    # ### end Alembic commands ###
