"""empty message

Revision ID: f8ce0141c696
Revises: 28a7c2817088
Create Date: 2023-01-12 23:53:13.039727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ce0141c696'
down_revision = '28a7c2817088'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depature_tbl',
    sa.Column('dep_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('depature_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus_tbl.bus_id'], ),
    sa.PrimaryKeyConstraint('dep_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depature_tbl')
    # ### end Alembic commands ###
