"""empty message

Revision ID: f979fc8be187
Revises: 97bd84899af2
Create Date: 2022-12-29 01:55:44.386385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f979fc8be187'
down_revision = '97bd84899af2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_tbl', 'l_name')
    op.drop_column('users_tbl', 'f_name')
    op.drop_column('users_tbl', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tbl', sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users_tbl', sa.Column('f_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users_tbl', sa.Column('l_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
